- name: Copy container config files
  copy:
    src: ./files/config
    dest: /root/
    mode: 0644

- name: docker-compose up
  shell: docker-compose up --detach --remove-orphans
  args:
    chdir: /root/config
