- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 1800
  become: true

- name: Upgrade all apt packages
  apt:
    upgrade: safe
  become: true

- name: Install Debian CLI packages
  apt:
    name: "{{ item }}"
    state: latest
  become: true
  with_items:
    - atool
    - autojump
    - build-essential
    - cmake
    - cowsay
    - curl
    - entr
    - exuberant-ctags
    - flac
    - flactag
    - git
    - htop
    - inotify-tools
    - libtool-bin
    - lltag
    - mediainfo
    - moreutils
    - mpv
    - ncdu
    - rsync
    - rtorrent
    - spell
    - tmux
    - toilet
    - tree
    - w3m
    - xsel
    - youtube-dl
