- git: repo=https://github.com/andsens/homeshick.git
       dest=~/.homesick/repos/homeshick
       update=no

- command: ~/.homesick/repos/homeshick/bin/homeshick clone https://github.com/lpil/dotfiles.git
  args:
    creates: ~/.homesick/repos/dotfiles


- command: ~/.homesick/repos/homeshick/bin/homeshick pull

- command: ~/.homesick/repos/homeshick/bin/homeshick --force link
