version: "3"

services:

  # Load balancer
  #
  traefik:
    image: traefik:1.5.4
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ~/data/acme.json:/etc/traefik/acme.json
    container_name: traefik

  # Fancy IRC web GUI
  #
  thelounge_irc:
    image: thelounge/thelounge:3.0.1-alpine
    container_name: thelounge_irc
    networks:
      - web
    restart: always
    volumes:
      - ~/data/thelounge:/var/opt/thelounge
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.thelounge_irc.frontend.rule=Host:irc.lpil.uk"
      - "traefik.thelounge_irc.port=9000"
      - "traefik.thelounge_irc.protocol=http"

  # Hackathon!
  #
  happylabs-frontend:
    image: lpil/happylabs-frontend:3
    container_name: happylabs-frontend
    networks:
      - web
    restart: always
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.happylabs-frontend.frontend.rule=Host:happylabs.lpil.uk"
      - "traefik.happylabs-frontend.port=80"
      - "traefik.happylabs-frontend.protocol=http"

  # Hackathon!
  #
  happylabs-api:
    image: lpil/happylabs-api-rust:10
    container_name: happylabs-api
    networks:
      - web
    restart: always
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.happylabs-api.frontend.rule=Host:happylabs-api.lpil.uk"
      - "traefik.happylabs-api.port=3000"
      - "traefik.happylabs-api.protocol=http"

  # Ghost blog for Pooky
  #
  ghost_pooky:
    image: ghost:2.19.1-alpine
    container_name: ghost_pooky
    networks:
      - web
    restart: always
    volumes:
      - ~/data/ghost_pooky:/var/lib/ghost/content
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.ghost_pooky.frontend.rule=Host:pooky.lpil.uk"
      - "traefik.ghost_pooky.port=2368"
      - "traefik.ghost_pooky.protocol=http"
    environment:
      - "url=https://pooky.lpil.uk"

networks:
  web:
