- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 1800
  become: true

- name: Upgrade all apt packages
  apt:
    upgrade: safe
  become: true

- name: Install Debian CLI packages
  apt:
    name: "{{ item }}"
    state: latest
  become: true
  with_items:

    - apache2-utils
    - atool
    - autoconf
    - autojump
    - build-essential
    - clang-format
    - cloc
    - cmake
    - cowsay
    - curl
    - dnsutils
    - entr
    - exuberant-ctags
    - flac
    - flactag
    - fuse
    - git
    - htop
    - inotify-tools
    - jq
    - libevent-dev
    - libncurses5-dev
    - libreadline-dev
    - libssl-dev
    - libtool-bin
    - libvips-tools
    - lltag
    - llvm
    - man-db
    - mediainfo
    - moreutils
    - mpv
    - ncdu
    - psmisc
    - python3-pip
    - rsync
    - rtorrent
    - speedtest-cli
    - spell
    - tmux
    - toilet
    - tree
    - w3m
    - wget
    - xsel
    - youtube-dl

- name: Install pip3 packages
  pip:
    name: "{{ item }}"
    executable: pip3
  with_items:
    - termtosvg
    # - black
