- apt: update_cache=yes cache_valid_time=1800
  sudo: true

- name: install packages
  apt: name={{ item }} state=latest
  sudo: true
  with_items:
    - atool
    - autojump
    - cowsay
    - curl
    - git
    - htop
    - moreutils
    - mpc
    - mpd
    - mpdscribble
    - mpv
    - ncmpcpp
    - tmux
    - toilet
    - tree
    - vim-athena
    - w3m
    - wicd-curses
    - youtube-dl

- include: pulse_audio.yml
- include: dotfiles.yml
- include: ssh.yml
