- apt: update_cache=yes cache_valid_time=1800
  sudo: true

- name: install packages
  apt: name={{ item }} state=latest
  sudo: true
  with_items:
    - exuberant-ctags
    - build-essential
    - cmake
    - libtool-bin

- include: docker.yml
# - include: elixir.yml
- include: fpp.yml
- include: golang.yml
- include: python.yml
- include: ruby.yml
- include: sqlite.yml
- include: elm.yml
